#!/bin/sh

#
# Pre-commit hook.  Contains elements of git's sample pre-commit hook.
#
fail_with_message () {
    echo ""
    echo "Aborting commit in pre-commit hook: $1"
    exit 1
}

# Get baseline to compare against.
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

# If there are whitespace errors, print the offending file names and fail.
git diff-index --check --cached $against -- || fail_with_message "Whitespace errors found."

# Check C++ format
./check-format.sh || fail_with_message "C++ style failures.  To identify/check failures, run:  ./check-format.sh"
